# Isotropic smoothing of image via Heat equation

## Assignment Explanation    
Heat, spatial domain이 존재할 때, 시간이 지나면서 열이 어떻게 퍼져나가는지 공간적으로 어떻게 전파되는지 모델링한 equation이다. x,y 축에서 미분 값 = $f(x,y)$의 gradient, 두 개의 channel을 가진다.   

### Laplace Operator   
$f(x, y)$ 라는 함수에 대해서, 함수 f를 L 적용, x,y점에서 evaluate한다. 하나의 값을 가지며, $Δf(x,y)$는 f와 같은 matrix를 갖는다. Gradient도 마찬가지다. 주어진 함수 f에 대해 gradient $∇f(x,y)$는 $f(x)$와 같은 사이즈인 matrix가 2개 있는 것이다. 벡터이기 때문이다. 그것을 x,y 좌표에서 evaluate 한다는 뜻이다. 이것은 df/dx의 값, df/dy 값 하나, 2개의 값을 가지는 벡터이며, LO는 값이 하나. x,y에서 evaluate 했다는 뜻이기 때문이다. 그런데 $∇f$는 matrix, 이것이 x,y축으로 미분한 것 $Δf$는 1차원 matrix가 된다. Evaluation한 것과, 전체 함수에 operate한 것은 다른 의미가 있다. f 함수는 special domain으로부터 real number로 가는 함수로 볼 수 있으며, LO 또한 같다. Gradient는 1차원 벡터로 가는 함수로 볼 수 있다. LO의 정의는 gradient를 2번 적용한 것으로 볼 수 있다. 이것이 갖는 의미는 gradient operator를 inner product한다는 것이다. 

### Heat equation    
heat equation의 정의는 먼저 함수 f가 어떤 special domain omega로 부터 real로 간다고 하면, u가 heat equation의 solution이라고 하자. 이것은 speical domain omega와 어떤 natural number -> real number, x,y에 대한 special domain에 대한 함수, t에 대한 함수로 만들 수 있다. x,y는 omega의 element. N은 시간을 표기하기 위한 임의의 domain. 시간에 따른 변화량. 초기값은 0일 때, $f(x,y)$

## import library

In [1]:
import numpy as np
import matplotlib.image as img
import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib.colors as colors
from skimage import color
from skimage import io

## load input image
- filename for the input image is 'barbara_color.jpeg'

In [2]:
I0 = io.imread('barbara_color.jpeg')

## check the size of the input image

In [3]:
# ++++++++++++++++++++++++++++++++++++++++++++++++++
# complete the blanks
# image size
num_row     = I0.shape[0]
num_column  = I0.shape[1]
num_channel = I0.shape[2]
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('number of rows of I0 = ', num_row)
print('number of columns of I0 = ', num_column)
print('number of channels of I0 = ', num_channel)

number of rows of I0 =  512
number of columns of I0 =  512
number of channels of I0 =  3


## convert the color image into a grey image

In [4]:
# ++++++++++++++++++++++++++++++++++++++++++++++++++
# complete the blanks
# 
I = color.rgb2gray(I0) # color to grey image

num_row     = I.shape[0] # row = x
num_column  = I.shape[1] # column = y
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('number of rows of I = ', num_row)
print('number of columns of I = ', num_column)

number of rows of I =  512
number of columns of I =  512


## normalize the converted image
- normalize the converted grey scale image so that its maximum value is 1 and its minimum value is 0

In [5]:
# ++++++++++++++++++++++++++++++++++++++++++++++++++
# complete the blanks
# 최소가 되는 값은 0, 최대는 1이 되어야 한다. 변환 비율에 따라 값이 변해야함
I = (I - np.min(I)) / (np.max(I) - np.min(I))
#
# ++++++++++++++++++++++++++++++++++++++++++++++++++

print('maximum value of I = ', np.max(I))
print('minimum value of I = ', np.min(I))

maximum value of I =  1.0
minimum value of I =  0.0


## define a function to compute the derivative of input matrix in x(row)-direction

- forward difference : $ I[x+1, y] - I[x, y] $ 

row 방향으로 +1 만들어야 한다.

#### Example with `np.roll`

In [14]:
x = np.arange(0,12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
x.shape

(3, 4)

In [11]:
x_1 = np.roll(x, -1, axis = 0)
x_1

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [12]:
x_1[2,:] = x_1[1,:] # last row index (n-1) = n-2 row index because index starts with 0.
x_1

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [21]:
I.shape

(512, 512)

### Forward difference

In [9]:
def compute_derivative_x_forward(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    IxPlusOne = np.roll(I, -1, axis = 0)
    IxPlusOne[511,:] = IxPlusOne[510,:]
    D = IxPlusOne - I
    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

### Backward difference

#### Example with `np.roll`

In [15]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
x_2 = np.roll(x, 1, axis = 0)
x_2[0,:] = x_2[1,:]
x_2

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

- backward difference : $ I[x, y] - I[x-1, y] $ 

In [12]:
def compute_derivative_x_backward(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    IxMinusOne = np.roll(I, 1, axis = 0)
    IxMinusOne[0,:] = IxMinusOne[1,:]
    D = I - IxMinusOne
    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

## define a function to compute the derivative of input matrix in y(column)-direction

### Forward Difference

#### Example with `np.roll`

In [16]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
x_3 = np.roll(x, -1, axis =1)
x_3

array([[ 1,  2,  3,  0],
       [ 5,  6,  7,  4],
       [ 9, 10, 11,  8]])

In [18]:
x_3[:,3] = x_3[:,2]
x_3

array([[ 1,  2,  3,  3],
       [ 5,  6,  7,  7],
       [ 9, 10, 11, 11]])

- forward difference : $ I[x, y+1] - I[x, y] $ 

In [15]:
def compute_derivative_y_forward(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    IyPlusOne = np.roll(I, -1, axis=1)
    IyPlusOne[:, 511] = IyPlusOne[:, 510]
    D = IyPlusOne - I

    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

### Backward Difference

#### Example with `np.roll`

In [20]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
x_4 = np.roll(x, 1, axis =1)
x_4

array([[ 3,  0,  1,  2],
       [ 7,  4,  5,  6],
       [11,  8,  9, 10]])

In [21]:
x_4[:,0] = x_4[:,1]
x_4

array([[ 0,  0,  1,  2],
       [ 4,  4,  5,  6],
       [ 8,  8,  9, 10]])

- backward difference : $ I[x, y] - I[x, y-1] $ 

In [22]:
def compute_derivative_y_backward(I):
    
    D = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    IyMinusOne = np.roll(I, 1, axis=1)
    IyMinusOne[:, 0] = IyMinusOne[:, 1]
    D = I - IyMinusOne
    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return D

## define a function to compute the laplacian of input matrix
- $\Delta I = \nabla^2 I = \frac{\partial^2 I}{\partial x^2} + \frac{\partial^2 I}{\partial y^2}$
- $\Delta I = I[x+1, y] + I[x-1, y] + I[x, y+1] + I[x, y-1] - 4 * I[x, y]$
- $\Delta I$ = derivative_x_forward - derivative_x_backward + derivative_y_forward - derivative_y_backward

In [23]:
def compute_laplace(I):
    
    laplace = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    IxPlusOne = np.roll(I, -1, axis = 0) # x forward
    IxPlusOne[511,:] = IxPlusOne[510,:]
    Dx_f = IxPlusOne - I
    
    IxMinusOne = np.roll(I, 1, axis = 0) # x backward
    IxMinusOne[0,:] = IxMinusOne[1,:]
    Dx_b = I - IxMinusOne

    IyPlusOne = np.roll(I, -1, axis=1) # y forward
    IyPlusOne[:, 511] = IyPlusOne[:, 510]
    Dy_f = IyPlusOne - I
    
    IyMinusOne = np.roll(I, 1, axis=1) # y backward
    IyMinusOne[:, 0] = IyMinusOne[:, 1]
    Dy_b = I - IyMinusOne

    laplace = Dx_f - Dx_b + Dy_f - Dy_b
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    
    return laplace

## define a function to compute the heat equation of data $I$ with a time step
- $I = I + \delta t * \Delta I$

In [18]:
def heat_equation(I, time_step):
    
    I_update = np.zeros(I.shape)
    
    # ++++++++++++++++++++++++++++++++++++++++++++++++++
    # complete the blanks
    #
    
    
    
    #
    # ++++++++++++++++++++++++++++++++++++++++++++++++++

    return I_update

## run the heat equation over iterations

In [19]:
def run_heat_equation(I, time_step, number_iteration):

    I_update = np.zeros(I.shape)

    for t in range(number_iteration):
        # ++++++++++++++++++++++++++++++++++++++++++++++++++
        # complete the blanks
        #
    
    
    
        #
        # ++++++++++++++++++++++++++++++++++++++++++++++++++

    return I_update

IndentationError: expected an indented block (Temp/ipykernel_23144/1902644636.py, line 15)

___

___

## functions for presenting the results

___

___

In [ ]:
def function_result_01():
    
    plt.figure(figsize=(8,6))
    plt.imshow(I0)
    plt.show()

In [ ]:
def function_result_02():
    
    plt.figure(figsize=(8,6))
    plt.imshow(I, cmap='gray', vmin=0, vmax=1, interpolation='none')
    plt.show()

In [ ]:
def function_result_03():

    L = compute_laplace(I)
    
    plt.figure(figsize=(8,6))
    plt.imshow(L, cmap='gray')
    plt.show()

In [ ]:
def function_result_04():

    time_step   = 0.25
    I_update    = heat_equation(I, time_step)
    
    plt.figure(figsize=(8,6))
    plt.imshow(I_update, vmin=0, vmax=1, cmap='gray')
    plt.show()

In [ ]:
def function_result_05():

    time_step           = 0.25
    number_iteration    = 128

    I_update = run_heat_equation(I, time_step, number_iteration)
    
    plt.figure(figsize=(8,6))
    plt.imshow(I_update, vmin=0, vmax=1, cmap='gray')
    plt.show()

In [ ]:
def function_result_06():

    time_step           = 0.25
    number_iteration    = 512

    I_update = run_heat_equation(I, time_step, number_iteration)
    
    plt.figure(figsize=(8,6))
    plt.imshow(I_update, vmin=0, vmax=1, cmap='gray')
    plt.show()

In [ ]:
def function_result_07():

    L = compute_laplace(I)

    value1 = L[0, 0]    
    value2 = L[-1, -1]    
    value3 = L[100, 100]    
    value4 = L[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)

In [ ]:
def function_result_08():

    time_step   = 0.25
    I_update    = heat_equation(I, time_step)

    value1 = I_update[0, 0]    
    value2 = I_update[-1, -1]    
    value3 = I_update[100, 100]    
    value4 = I_update[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)

In [ ]:
def function_result_09():

    time_step           = 0.25
    number_iteration    = 128

    I_update = run_heat_equation(I, time_step, number_iteration)

    value1 = I_update[0, 0]    
    value2 = I_update[-1, -1]    
    value3 = I_update[100, 100]    
    value4 = I_update[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)

In [ ]:
def function_result_10():

    time_step           = 0.25
    number_iteration    = 512

    I_update = run_heat_equation(I, time_step, number_iteration)

    value1 = I_update[0, 0]    
    value2 = I_update[-1, -1]    
    value3 = I_update[100, 100]    
    value4 = I_update[200, 200]

    print('value1 = ', value1)
    print('value2 = ', value2)
    print('value3 = ', value3)
    print('value4 = ', value4)

___

___

# results

___

___

In [ ]:
number_result = 10

for i in range(number_result):
    title = '## [RESULT {:02d}]'.format(i+1)
    name_function = 'function_result_{:02d}()'.format(i+1)

    print('**************************************************')
    print(title)
    print('**************************************************')
    eval(name_function)